### ISSUE TITLE
Mismatched Appendix Figure and Caption

### ISSUE THREAD

**Issue by relh** [McGill-NLP/AURORA#5]
![Screenshot from 2024-09-12 09-53-21](https://github.com/user-attachments/assets/c8bf6c31-9f25-4f52-872a-bbbe3cffdce4)

In H.1 in Figure 15 (c) It seems like a caption is here that isn't associated with the fire hydrant in the dataset. I'm assuming this is a typo but maybe double check the caption/image pairings in case there's an error.

**Comment by BennoKrojer** [comment]
Hi, great catch! That's indeed a typo and was probably some last minute change when making the appendix :)

I will fix it now!
Best,
Benno

**Comment by BennoKrojer** [comment]
Close
