### ISSUE TITLE
Running Evaluation on Aurora-Bench

### ISSUE THREAD

**Issue by alphacoder01** [McGill-NLP/AURORA#8]
Hi,

It seems the json files corresponding to different tasks are missing.
As mentioned in the  [(README.MD)](https://github.com/McGill-NLP/AURORA?tab=readme-ov-file#reproduce-evaluation)
Running `python disc_edit.py --task "whatsup"` leads to the following error
```python
FileNotFoundError: [Errno 2] No such file or directory: 'data/whatsup/itm_test.json'
```

Can the authors please provide the missing files/correct instructions for running the evaluation with proposed metric.

Thanks!!

**Comment by alphacoder01** [comment]
Hi @BennoKrojer 
I was wondering if there have been any updates or plans to release the files and instructions for evaluation.

Thanks in Advance!!

**Comment by BennoKrojer** [comment]
Hi Ashish,

sorry for the delay, I somehow missed this! I will look into it later today.

Best,
Benno

**Comment by BennoKrojer** [comment]
Hi,

To unblock you fast I just uploaded the data for now but you will have to change some file paths unfortunately inside the dataloader (edit_dataset.py). I am quite busy the next weeks but I hope this is better than nothing and with changing a few lines you should be good to go!

Here are the jsons: https://github.com/McGill-NLP/AURORA/tree/main/disc_edit_data

Best,
Benno
